workflows:
  android-workflow:
    name: Android Build
    instance_type: mac_mini
    max_build_duration: 60
    environment:
      flutter: stable
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug
    artifacts:
      - build/**/outputs/apk/debug/*.apk
